<body>  
<?php 
$interfaces=[
[
'name'=>'GetVerificationCode',
'url'=>'login/get-verification-code',
'params'=>'phone'
],
[
'name'=>'AddSupplyment',
'url'=>'supplyment/add-supplyment',
'params'=>'userid,city,district,court,lat,lng,area,price,floor,totalfloor,room,hall,kitchen,toilet,decorate,apartmenttype,renttype,cooking,pay,deposit,airconditioning,washingmachine,refrigerator,shower,broadband,accommodationproof,contactor,tel,description'
],
[
'name'=>'AddRequirement',
'url'=>'requirement/add-requirement',
'params'=>'userid,city,district,court,lat,lng,area,room,hall,kitchen,toilet,decorate,apartmenttype,renttype,cooking,airconditioning,washingmachine,refrigerator,shower,broadband,accommodationproof,contactor,tel,description'
],
[
'name'=>'GetSupplyment',
'url'=>'supplyment/get-supplyment',
'params'=>'city,district,lat,lng'
],
[
'name'=>'GetRequirement',
'url'=>'requirement/get-requirement',
'params'=>'city,district,lat,lng'
],
[
'name'=>'GetSupplymentList',
'url'=>'supplyment/get-supplyment-list',
'params'=>'lng,lat,start,count'
],
[
'name'=>'GetRequirementList',
'url'=>'requirement/get-requirement-list',
'params'=>'lng,lat,start,count'
],
[
'name'=>'GetRequirementById',
'url'=>'requirement/get-requirement-by-id',
'params'=>'requirementId'
],
[
'name'=>'GetSupplymentById',
'url'=>'supplyment/get-supplyment-by-id',
'params'=>'supplymentId'
],
[
'name'=>'GetAgentList',
'url'=>'user/get-agent-list',
'params'=>'lng,lat'
],
[
'name'=>'UpdateUserToAgent',
'url'=>'user/update-user-to-agent',
'params'=>'id,lng,lat'
],
];
						
foreach($interfaces as $interface){
?>
<a href = "interfaces/simpleinterface.php?name=<?=$interface['name']?>&url=<?=$interface['url']?>&params=<?=$interface['params']?>" target = "frame2"><?=$interface['name']?></a><br/>
<?php 
}
?>

</body>  

